### ISSUE TITLE
fontHeight not read while hasFontClass is true in TagDefineEditText

### ISSUE THREAD

**Issue by 0xE1** [claus/as3swf#44]
fontHeight should be read when hasFont or hasFontClass is true.

Currently it's only being read when hasFont is true.

Ref: http://sourceforge.net/adobe/swfinvestigator/code/17/tree/trunk/SWFInvestigator/src/decompiler/swfdump/TagDecoder.as#l1191

**Comment by sbijoshj** [comment]
Oh hey this might be fixed now in 22b520fab74093bef5eb6d61d3593d337289003e

**Comment by claus** [comment]
Ya it is! Closing.
