### ISSUE TITLE
Parse DefineBitsLossless into a BitmapData

### ISSUE THREAD

**Issue by henke37** [claus/as3swf#46]
It's a waste of time for users of the parser to sit and manually write pixel data decoders when the parser should be doing it for them.

**Comment by makc** [comment]
but then same can be said about jpegs, for example.

**Comment by claus** [comment]
@henke37, someone could write a decoder that does what you are asking and release it as a separate library. It was certainly not my intention to waste people's time when i wrote this library, i just tried to keep it manageable in scope.

**Comment by makc** [comment]
@claus oh hey, you're still around! what about two open PRs then?

**Comment by henke37** [comment]
"someone could write a decoder that does it". Yes, you. Because this is very much something expected from a library for parsing swf files. If you need to read the swf specs to do it then by all means it goes in a swf parsing library.

**Comment by claus** [comment]
Look, guys. I haven't done _any_ Flash dev for years. _For me personally_, Flash is a dead technology (you might disagree, and that's fine). I don't even have any tools installed to compile this project.

The beautiful thing about open source is that anyone, including you, can fork this repo and implement whatever they desire. Run with it. Also, you're free to contact the author to ask nicely why it is that there haven't been any updates for more than 3 years. It is likely you get a equally nice reply.

The ugly thing about open source is that there are people who appear to think open source authors owe them something for whatever reason (a feature not implemented, a bug not fixed, etc). _I don't owe you anything_. If you think i do, i'll kindly ask you to write your own software and please not use mine. Thanks, and good luck.

Locking this thread.
